```{r}
Sys.setenv(CFBD_API_KEY = "nYYDD4adQNxIjanGAuq5+7QJnagAevOptlhW1KHzZMvML+OSi3CwZSUsw9O58aM6")
```



```{r}
library(tidyverse)
```

```{r}
library(cfbfastR)
```


```{r}
cfbd_team_info(conference = "B1G")
```

```{r}
b1g_2021 <- cfbd_game_info(year = 2021, conference = "B1G")
b1g_2022 <- cfbd_game_info(year = 2022, conference = "B1G")
b1g_2023 <- cfbd_game_info(year = 2023, conference = "B1G")
b1g_2024 <- cfbd_game_info(year = 2024, conference = "B1G")

b1g <- bind_rows(b1g_2021, b1g_2022, b1g_2023, b1g_2024)
```

```{r}
home <- b1g |>
  mutate(point_diff = home_points - away_points) |>
  filter(!neutral_site, !is.na(attendance))
```

```{r}
home |>
  group_by(win = point_diff > 0) |>
  summarize(avg_attendance = mean(attendance))
```

```{r}
home <- b1g |>
  filter(!neutral_site, !is.na(attendance)) |>
  mutate(win = home_points > away_points)
```

```{r}
team_summary <- home |>
  group_by(home_team, win) |>
  summarize(
    games = n(),
    avg_home_pts = mean(home_points),
    avg_opp_pts  = mean(away_points),
    avg_attendance = mean(attendance)
  ) |>
  arrange(home_team, desc(win))
```

```{r}
big_ten_teams <- c(
  "Illinois", "Indiana", "Iowa", "Maryland", "Michigan", "Michigan State",
  "Minnesota", "Nebraska", "Northwestern", "Ohio State", "Penn State",
  "Purdue", "Rutgers", "Wisconsin", "USC", "UCLA", "Oregon", "Washington"
)

b1g_only <- team_summary |> 
  filter(home_team %in% big_ten_teams)
```

```{r}
b1g_only_long <- home |>
  filter(home_team %in% big_ten_teams, !neutral_site, !is.na(attendance)) |>
  mutate(result = if_else(home_points > away_points, "Win", "Loss")) |>
  group_by(home_team, result) |>
  summarize(
    games = n(),
    avg_home_pts = mean(home_points),
    avg_opp_pts  = mean(away_points),
    avg_attendance = mean(attendance)
  ) |>
  arrange(home_team, desc(result))
```


I decided the change what I was doing and use the cfbfastR for this project. There are 34 rows, two for each Big Ten Team --- one for losses and one for wins which shows the attendence at the home game and the stats for wins/losses. 


```{r}
line_teams <- c("Maryland", "Ohio State", "Michigan", "Penn State", "Indiana", "Wisconsin", "UCLA")

b1g_subset <- b1g_only_long |>
  filter(home_team %in% line_teams)

ggplot(b1g_subset, aes(x = result, y = avg_attendance, group = home_team, color = home_team)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Maryland sees the largest drop off in attendence in wins vs losses.
    The Terps are losing the more attended games compared to the conference.",
    x = "",
    y = "Avg. Attendance"
  ) +
  theme_minimal()
```

